### ISSUE TITLE
Need some basic shell commands early on (cd ..    etc.)   

### ISSUE THREAD

**Issue by andrew-edwards** [quantitative-biology/module-1-git#2]

**Comment by andrew-edwards** [comment]
Also instructions on use of text editors, including for .md files to edit README.md.

**Comment by andrew-edwards** [comment]
Do we really need any commands beyond `cd <directory>` and `cd ..` ? @kcudding ? Think that's all we used in the talks.

**Comment by kcudding** [comment]
how did we open a new text file?

**Comment by andrew-edwards** [comment]
I do right-click new-text-file (though usually I'd just create in Emacs as it's quicker). I can add that to the info? I can check that `cd` and `dir` (if needed) are same in Mac - think they are.
