### ISSUE TITLE
tester comments/ideas

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/module-1-git#6]
## mod 1 git and githhub
 - [x] a bit too long
 - [x] material on navigating on github 
 - [x] material on R and github (separate?)
 - [x] repetition in 2.4
 - [x] collaboration exercise should be removed - leaving in, it says "If you have a colleague available"
 - [x] increase material under powershell? 2.2.7
 - [x] 2.2.12 confusing to figure out how to copy file
 - [x] 2.213 confusing for a newbie
 - [x] more guided step by step instructions and reference pictures, or a section purely on learning how to navigate Github
 - [x] put definitions section earlier
 - [x] notebook++ link is broken
 - [x] more videos
 - [x] alias codes did not work
 - [x] collaboration video needs a fix at 9 mins
 - [x] more graphics - not really added, but clearer now that watch the video first then the commands are all given again in the text for reference
 - [x] github module should mention tracking issue, and then point to the bookdown issue board - Andy didn't quite understand this, think it means to show a demo of an Issue, which I think is done.

idea: sections as follows 
 - [x] 1. your collaborator uses github--> navigating the site (R packages on github)
 - [x] 2. you want to use github for version control ---> setting it up
 - [x] 3. you want to use github to collaborate
 - [x] 4. github with R

Also:
 - [x] Rstudio demo at the end

**Comment by andrew-edwards** [comment]
Also, for videos:
 - [x] record new navigate-GitHub video
 - [x] re-record intro video, splitting into two maybe.
 - [x] re-record collaboration video
 - [x] put them on YouTube and embed better into markdown? Currently a link to google drive.

Copyediting:
 - [x] consistency of formatting, stick with italics for filenames so not confusing with `this` for commands
 - [x] read through advanced section again a bit carefully
